export const projects = [
  {
    title: 'DevBills',
    url: 'https://dev-billss.netlify.app/',
    category: 'Aplicação',
    stack: ['React', 'TypeScript', 'Tailwind'],
    updatedAt: '2025-08-08',
    thumb: '/devbills.png.png',
  },
  {
    title: 'Manhaus',
    url: 'https://manhous.com.br/',
    category: 'E-commerce',
    stack: ['Frontend'],
    updatedAt: '2025-08-08',
    thumb: '/manhaus.png.png',
  },
  {
    title: 'JR movies',
    url: 'https://jrmovies.netlify.app/',
    category: 'Front-end',
    stack: ['Next.js', 'React'],
    updatedAt: '2024-10-01',
    thumb: '/JRmovies.png',
  },
  {
    title: 'clone netFlix',
    url: 'https://jaymisom123.github.io/cafeteria/',
    category: 'Landing Page',
    stack: ['HTML', 'CSS', 'JS'],
    updatedAt: '2024-07-10',
    thumb: '/netfilx.png',
  },
  {
    title: 'JR <CodeIA>',
    url: 'https://jrcodeia.netlify.app/',
    category: 'Front-end',
    stack: ['React'],
    updatedAt: '2024-06-15',
    thumb: '/codeIA.png',
  },
  {
    title: 'Cafeteria Landing Page',
    url: 'https://jaymisom123.github.io/cafeteria/',
    category: 'Landing Page',
    stack: ['HTML', 'CSS', 'JS'],
    updatedAt: '2024-05-20',
    thumb: '/cafeteira.png',
  },
  {
    title: 'Burger show',
    url: 'https://github.com/Jaymisom123/devburger-interface',
    category: 'Repositório',
    stack: ['React', 'Styled Components'],
    updatedAt: '2024-04-30',
    thumb: '/devburger.png',
  },
  {
    title: 'Sulla Jeans',
    url: 'https://sullajeans.netlify.app/',
    category: 'E-commerce',
    stack: ['React', 'Tailwind'],
    updatedAt: '2024-03-12',
    thumb: '/sullajeans.png',
  },
  {
    title: 'Loja de Roupas',
    url: 'https://jaymisom123.github.io/loja/',
    category: 'Landing Page',
    stack: ['HTML', 'CSS'],
    updatedAt: '2024-02-05',
    thumb: '/loja.png',
  },
  {
    title: 'Clínica JR',
    url: 'https://clinicajr.netlify.app/',
    category: 'Landing Page',
    stack :['HTML', 'CSS', 'JS'],
    updatedAt: '2024-01-18',
    thumb: '/clinicajr.png',
  },
  {
    title: 'JR studio',
    url: 'https://jrstudio.netlify.app/',
    category: 'Portfólio',
    stack: ['HTML', 'CSS', 'JS'],
    updatedAt: '2024-12-01',
    thumb: '/jrstudio.png',
  },
  {
    title: 'Metropolitana',
    url: 'https://costrtutorametropolitana.netlify.app/',
    category: 'Portfólio',
    stack: ['HTML', 'CSS', 'JS'],
    updatedAt: '2024-12-01',
    thumb: '/metropolitana.png',
  },
  {
    title: 'Assistência Técnica',
    url: 'https://autoflowsitemario.netlify.app/',
    category: 'Portfólio',
    stack: ['React', 'Tailwind'],
    updatedAt: '2023-12-01',
    thumb: '/mario.png.png',
  },
  {
    title: 'JR Justiça',
    url: 'https://advocacymodel.netlify.app/',
    category: 'Portfólio',
    stack: ['HTML', 'CSS', 'JS'],
    updatedAt: '2024-12-01',
    thumb: '/justiça.png',
  },
  {
    title: 'Odontológia',
    url: 'https://ferreiramatosodontologia.netlify.app/',
    category: 'Portfólio',
    stack: ['React','Sass'],
    updatedAt: '2023-12-01',
    thumb: 'Odontológia.png',
  },
];


